spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf-8&useSSL=false

  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8888
# sql查看
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#   MP支持以下4中主键策略，可根据需求自行选用
#    主键注解 @TableId
#    value	字段值（驼峰命名方式，该值可无）
#    type	主键 ID 策略类型（ 默认 INPUT ，全局开启的是 ID_WORKER
#    IdType.AUTO	数据库ID自增
#    IdType.INPUT	用户输入ID
#    IdType.ID_WORKER	全局唯一ID，内容为空自动填充（默认配置）
#    IdType.UUID	全局唯一ID，内容为空自动填充

#      查询方式	说明
#      setSqlSelect	设置 SELECT 查询字段
#      where	WHERE 语句，拼接 + WHERE 条件
#      and	AND 语句，拼接 + AND 字段=值
#      andNew	AND 语句，拼接 + AND (字段=值)
#      or	OR 语句，拼接 + OR 字段=值
#      orNew	OR 语句，拼接 + OR (字段=值)
#      eq	等于=
#      allEq	基于 map 内容等于=
#      ne	不等于<>
#      gt	大于>
#      ge	大于等于>=
#      lt	小于<
#      le	小于等于<=
#      like	模糊查询 LIKE
#      notLike	模糊查询 NOT LIKE
#      in	IN 查询
#      notIn	NOT IN 查询
#      isNull	NULL 值查询
#      isNotNull	IS NOT NULL
#      groupBy	分组 GROUP BY
#      having	HAVING 关键词
#      orderBy	排序 ORDER BY
#      orderAsc	ASC 排序 ORDER BY
#      orderDesc	DESC 排序 ORDER BY
#      exists	EXISTS 条件语句
#      notExists	NOT EXISTS 条件语句
#      between	BETWEEN 条件语句
#      notBetween	NOT BETWEEN 条件语句
#      addFilter	自由拼接 SQL
#      last	拼接在最后，例如：last("LIMIT 1")